version: '3'
services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"

  web2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
